# Generated by Django 5.2.7 on 2025-10-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewscore',
            name='review',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.review'),
        ),
    ]
